### ISSUE TITLE
shutting down instructions not working

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/docker-existdb#1]
I can execute shutdown from the Dashboard resulting in.
![screenshot 2017-11-09 12 21 53](https://user-images.githubusercontent.com/6205362/32603084-bf07f6d2-c548-11e7-904f-55ee3b794b52.png)

but ``CTRL-C`` in terminal via ``Exec`` or ``Docker CLI`` ( I use kitematic) on the instance doesn't seem to do anything.

**Comment by adamretter** [comment]
@duncdrum I don't know what `Exec` you refer too. Also I am not using Kinematic. The instructions are for working from the terminal with Bash and Docker tools. On Mac I have tested this with both Terminal.app and also Alacritty.

<img width="1017" alt="screen shot 2017-11-09 at 12 02 26" src="https://user-images.githubusercontent.com/1264057/32604570-fa296a3c-c545-11e7-9ec9-7719683c99bb.png">

If you find a different process for `Exec` or `Docker CLI` I would be happy to add it to the documentation.

I have also just noticed you can use `docker stop <container name>` to shut down eXist and the container. I have added that to the `README.md`.

**Comment by duncdrum** [comment]
``exec`` and ``Dockercli``are the names of the kitematic UI buttons that open bash on image or dockerCLI (terminal). Using ``Stop`` in the ui seems to work. So maybe switch to that for the readme
