### ISSUE TITLE
4.4.0 release?

### ISSUE THREAD

**Issue by bkcsfi** [evolvedbinary/docker-existdb#12]
Can you please push an updated docker image for 4.4.0

**Comment by adamretter** [comment]
There are now official Docker images from the eXist-db project available on Docker Hub - https://hub.docker.com/r/existdb/existdb/tags/

Perhaps those would suit you better?

**Comment by bkcsfi** [comment]
yes, that's great I will use those images instead.

Please note the blog http://exist-db.org/exist/apps/wiki/blogs/eXist/eXistdb440  doesn't mention these new images.
