### ISSUE TITLE
Complete documentation about admin user 

### ISSUE THREAD

**Issue by gmella** [evolvedbinary/docker-existdb#2]
Hi,

Very nice project!! Excited, I just tried and didn't manage to find quickly the default admin credentials. I tried without password as admin and it works ;)

Documentation could give this information and point to the change default password instructions.

Best regards,
--
Guillaume

**Comment by adamretter** [comment]
@gmella Thanks for the feedback :-)

I have updated the README.md as suggested with details of the default username and password.
