### ISSUE TITLE
HTTP POST to top level RESTXQ service application "Content-type: application/xquery" fails in minimal tagged images

### ISSUE THREAD

**Issue by rapport** [evolvedbinary/docker-existdb#4]
I get a HTTP 405 error returned when I HTTP POST to any *.xqm RESTXQ top level service application "Content-type: application/xquery" with any of the minimal tagged docker images ( e.g. exist-db:eXist-3.6.0-minimal & e.g. exist-db:eXist-3.5.0-minimal)  and this works fine from any of the images not tagged miminal. Not sure if this is a feature or bug.  

Also, no idea how to read the log files in these images- maybe it would be a good idea to add options to save the logs such as the RESTXQ log to a volume as done with the 'exist-data' then it could be easiest to debug and isolate problems like this.

Many thanks evolvedbinary for creating these great images and sharing!

**Comment by adamretter** [comment]
Ho @rapport, can you please check your checksum for your `eXist-3.6.0-minimal` image. Our initial release of that was faulty, and we had to overwrite it on Dockerhub with a fixed version. I believe the fixed version should have Image ID  `77b4a8275a1a`.

If yours does not, you will need to `docker rmi evolvedbinary/exist-db:eXist-3.6.0-minimal` locally, and then pull it again from Dockerhub.

Let me know if that helps?

**Comment by rapport** [comment]
I have checked and I do have this image... To check I ran 'docker images --digests' - it shows image  '77b4a8275a1a' from 2 weeks ago!

The process I follow is I create lots of *.xqm file along the lines....
curl -d "xquery version '3.0'; APP HERE DETAILS THAT receives POST" -H "Content-type: application/xquery" -X PUT http://admin:admin@localhost:9080/exist/rest/db/test.xqm

Then I have a standard HTML page with a POST method that sends POST data to these app URLs. It only returns 405 error on minimal docker images.

**Comment by adamretter** [comment]
After you have stored your `xqm` files, can you check that they have been compiled and registerd by calling the function `rest:resource-functions()`. The namespace of that function should be `http://exquery.org/ns/restxq`.

You could also check `$EXIST_HOME/webapp/WEB-INF/logs/restxq.log`. I think inside the Docker images, that would be `/exist/webapp/WEB-INF/logs/restxq.log`.

**Comment by rapport** [comment]
Ok thanks for the pointers to the function and also the log file... I'll feedback at some point if I work out how to do this. I was aware of the log file but couldn't work out how to get into the container to access and debug - I am used to running something like 'sudo docker exec -it exist /bin/bash' and then finding the file in the container but as there is no bash in 'distroless container'  I am not familar how to do it although the approach looks very good!

**Comment by adamretter** [comment]
@rapport Any updates please?
