### ISSUE TITLE
[feature] support docker-compose

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/docker-existdb#5]
Since this is quickly becoming the canonical eXist-db base image, add `docker-compose.yml` so folks can upgrade their production and test images by running:
`docker-compose up`
This would make it easier to keep the underlying eXist version in line with the latest release.

[docs](https://docs.docker.com/compose/overview/)

**Comment by adamretter** [comment]
@duncdrum Do you want to send a PR?

**Comment by duncdrum** [comment]
see duncdrum/exist-docker

**Comment by duncdrum** [comment]
see eXist-db/docker-existdb
